Develop: init Project
bianjieai/iobscan-ibc-explorer-backend pull request #1
Opened 2021-09-17 03:00 UTC by tongzhuomasi

init Project

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +          ibcTx.sc_tx_info.msg_amount.msg.timeout_height.revision_height;
msg 存储结构优化

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +        if (ibcHeight > height || ibcTime > time) {
(ibcHeight < height || ibcTime < time)

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +            packet_id: ibcTx.sc_tx_info.msg_amount.msg.packet_id,
msg

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +                  msg_amount: msg,
msg

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +                const result = this.ibcTxModel.updateIbcTx(ibcTx);
clear 'const result ='

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +                const packet_data = JSON.parse(attr.value);
JSON.parse 容错

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +                  .join('');
.join('/')

2021-09-17 13:28 UTC, hangts commented on src/task/ibc_tx.task.service.ts
> +    });
update_at 不会更新

2021-09-17 13:28 UTC, hangts commented on src/types/gov.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on src/types/schemaTypes/tokens.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on src/types/schemaTypes/tx.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on src/types/schemaTypes/txType.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on src/types/schemaTypes/validators.interface.ts
> +
delete

2021-09-17 13:28 UTC, hangts commented on src/types/statistics.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on src/types/tx.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on src/types/validators.interface.ts
> +}
delete

2021-09-17 13:28 UTC, hangts commented on tool.sh
> +fi
改进

2021-09-17 13:31 UTC, hangts commented on src/schema/ibc_chain.schema.ts
> +import * as mongoose from 'mongoose';
1.函数声明需要明确入参及出参类型
 2.create_at、update_at 建议使用：
   create_at: {
	    	type:Number,
	    	default:getTimestamp(),
	    },
	    update_at: {
	    	type:Number,
	    	default:getTimestamp(),
	    }
3.schema 中仅做数据库操作，数据处理建议放到 service 中

2021-09-24 09:10 UTC, hangts approved these changes

2021-09-24 10:09 UTC, kaifei-bianjie requested changes
must resolve all conversations before merge @tongzhuomasi @hangts

2021-09-26 06:22 UTC, hangts commented on src/dto/ibc_tx.dto.ts
> +    update_at: string;
功能未完成的 dto

2021-09-26 06:22 UTC, hangts commented on src/dto/ibc_tx.dto.ts
> +    update_at: string;
功能未完成的 dto 
list data 使用 bundleData 处理

2021-09-26 06:22 UTC, hangts commented on src/dto/http.dto.ts
> +    this.channels = channels || [];
list data 使用 bundleData 处理

2021-09-26 06:22 UTC, hangts commented on src/dto/ibc_chain.dto.ts
> +    }
list data 使用 bundleData 处理

2021-09-26 06:22 UTC, hangts commented on src/service/ibc_statistics.service.ts
> +    return result;
data 未使用 dto

2021-09-26 09:13 UTC, hangts approved these changes

2021-09-26 09:17 UTC, merged